---
- name: Install xl2tpd
  pacman:
    name: xl2tpd
    state: latest
  become: yes


- name: Deploy xl2tpd.conf
  template:
    src: xl2tpd.conf.j2
    dest: /etc/xl2tpd/xl2tpd.conf
    backup: yes
  become: yes


- name: Deploy /etc/ppp/options.l2tpd.{{ vpn_name }}
  template:
    src: options.l2tpd.j2
    dest: /etc/ppp/options.l2tpd.{{ vpn_name }}
    mode: 0600
    backup: yes
  become: yes


- name: Set credentials
  lineinfile:
    dest: /etc/ppp/chap-secrets
    line: "{{ vpn_user_name }} * {{ vpn_user_password }}"
  become: yes
