---
# NOTE: You must set PATH environment variable (PATH=$HOME/.rbenv/bin:$PATH)

- name: Clone rbenv repository
  git:
    dest: "{{ ansible_env.HOME }}/.rbenv"
    repo: https://github.com/rbenv/rbenv.git
    clone: yes
    update: yes


- name: Clone ruby-build repository
  git:
    dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
    repo: https://github.com/sstephenson/ruby-build.git
    clone: yes
    update: yes


- name: Install Ruby
  shell: |
    rbenv versions | grep -F "{{ rbenv_ruby_version }}" || rbenv install "{{ rbenv_ruby_version }}"


- name: Set global rbenv version
  shell: |
    rbenv global "{{ rbenv_ruby_version }}"


- name: Install Development tools
  gem:
    name: "{{ item }}"
    state: latest
    executable: "{{ ansible_env.HOME }}/.rbenv/shims/gem"
    user_install: no
  with_items:
    - bundler
    - rubocop
    - refe2
    - pry
    - pry-theme
