---
- hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        # Network management tools
        - iw
        - wpa_supplicant
        - wpa_actiond
        - dialog

        # Accessing remote server
        - openssh
        - rsync
        - remmina
        - libvncserver
        - freerdp
        - sshfs
        - wget

        # Development tools
        - vim
        - zsh
        - git
        - tmux
        - jq
        - ctags
        - nmap
        - pkgfile
        - bind-tools

        # Window manager or X relevant tools
        - i3
        - xorg-server
        - xorg-xinit
        - xorg-xsetroot
        - xorg-xset
        - xorg-setxkbmap
        - xorg-xmodmap
        - xorg-xrandr
        - xf86-input-synaptics
        - xclip
        - xsel
        - xautolock
        - fcitx-mozc
        - fcitx-configtool
        - xfce4-terminal
        - dmenu

        # Fonts
        - ttf-dejavu
        - ttf-inconsolata
        - ttf-droid
        - ttf-hanazono

        # Web browser
        - chromium
        - firefox
