---
- hosts: localhost
  connection: local
  roles:
    - role: ruby
      tags:
        - ruby
        - development
    - role: python
      tags:
        - python
        - development
    - role: rust
      tags:
        - rust
        - development
  vars:
    - rbenv_ruby_version: "2.3.1"
