---
- include: hypervisor.yml
  when: ansible_os_family == 'Archlinux'


- include: container.yml.yml
  when: ansible_os_family == 'Archlinux'


- include: vpn.yml
  when: ansible_os_family == 'Archlinux'


- include: dev-tool.yml
