---
- name: Install Rust
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup-installer.sh
    mode: 0700


- name: Run rustup installer
  shell: |
    /tmp/rustup-installer.sh -y --default-toolchain stable


- name: Install some commands
  shell: |
    cargo install {{ item }}
  with_items:
    - rusty-tags
    - rustfmt
