---
- name: Install Python
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - python
    - python-pip
    - python2
    - python2-virtualenv
    - python-numpy
    - python-pandas
    - python-scipy
    - python-statsmodels
    - python-matplotlib
    - python-seaborn
    - python-click
    - ipython
    - flake8
  become: yes

# awscli
