---
- name: Install libvirt
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - libvirt
    - virt-install
    - virt-manager
    - dnsmasq
    - ebtables
    - dmidecode
    - qemu
  become: yes
  notify:
    - libvirt_restart


- name: Set libvirtd.conf
  template:
    src: libvirtd.conf.j2
    dest: /etc/libvirt/libvirtd.conf
    backup: yes
  become: yes
  notify:
    - libvirt_restart


- name: Add users into libvirt group
  user:
    append: yes
    name: "{{ item }}"
    groups: libvirt
  with_items: "{{ libvirt_users }}"
  become: yes


- name: Add users into kvm group
  user:
    append: yes
    name: "{{ item }}"
    groups: kvm
  with_items: "{{ libvirt_users }}"
  become: yes


- name: Start libvirt
  service:
    name: libvirtd.service
    state: started
  become: yes
