---
- hosts: localhost
  connection: local
  tasks:
    - name: Install packages
      pacman:
        name: "{{ item }}"
        state: latest
      with_items:
        # Network management tools
        - iw
        - wpa_supplicant
        - wpa_actiond
        - dialog
        - wol

        # Window manager or X relevant tools
        - i3
        - xorg-server
        - xorg-xinit
        - xorg-xsetroot
        - xorg-xset
        - xorg-setxkbmap
        - xorg-xmodmap
        - xorg-xrandr
        - xorg-xinput
        - xorg-xev
        - xorg-xbacklight
        - xf86-input-synaptics
        - xf86-video-intel
        - xclip
        - xsel
        - xautolock
        - xdotool
        - fcitx-im
        - fcitx-mozc
        - fcitx-configtool
        - dmenu
        - libvdpau-va-gl

        # Fonts
        - ttf-dejavu
        - ttf-inconsolata
        - ttf-symbola
        - noto-fonts
        - noto-fonts-cjk

        # Sound/Video
        - alsa-utils
        - pulseaudio
        - pavucontrol
        - easytag
        - rhythmbox
        - vlc

        # Accessing remote server
        - openssh
        - rsync
        - remmina
        - libvncserver
        - freerdp
        - wget

        # Mount tools
        - sshfs
        - cifs-utils
        - autofs

        # Development tools
        - vim
        - zsh
        - git
        - terminator
        - tmux
        - jq
        - ctags
        - nmap
        - pkgfile
        - bind-tools
        - strace
        - ltrace

        # System monitoring tools
        - lsof
        - dstat
        - wireshark-cli
        - lshw

        # Web browser
        - chromium
        - firefox

        # Other utilities
        - cdrtools
        - abcde

        # E-mail
        # - msmtp
        # - getmail
        # - procmail
