---
- hosts: localhost
  connection: local
  roles:
    - role: rust
      tags:
        - rust
        - development
    - role: go
      tags:
        - go
        - development
    - role: ruby
      tags:
        - ruby
        - development
    - role: python
      tags:
        - python
        - development
    - role: javascript
      tags:
        - javascript
        - development
    - role: gcloud
      tags:
        - gcloud
        - development
    - role: aws
      tags:
        - aws
        - development
  vars:
    - rbenv_ruby_version: '2.4.1'
    - gcloud_version: '145.0.0'
