---
- hosts: localhost
  connection: local
  vars_files:
    - .secrets.yml
  roles:
    - role: sysctl
      tags:
        - sysctl
    - role: openswan
      tags:
        - openswan
    - role: xl2tpd
      tags:
        - xl2tpd

  post_tasks:
    - name: Start openswan
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - openswan.service
        - xl2tpd.service
      become: yes


    - name: Up {{ vpn_name }}
      shell: |
        ipsec auto --up {{ vpn_name }}
      become: yes


    - name: Connect L2TP
      shell: |
        mkdir -p /var/run/xl2tpd && \
        echo "c {{ vpn_name }}" > /var/run/xl2tpd/l2tp-control
      become: yes

    # FIXME: ppp0

    - name: Wait for interface
      shell: |
        for x in 1 2 3 4 5; do sleep 1; ip link show dev ppp0 | grep -q inet && break || continue; done


    - name: Set routing
      shell: |
        current_gateway=`ip route show | grep default | awk '{print $3}'` && \
        ip route add "{{ vpn_server_ip }}" via ${current_gateway} && \
        ip route delete default via ${current_gateway} && \
        ip route add default dev ppp0
      become: yes
