---
- name: Install docker
  pacman:
    name: docker
    state: latest
  become: yes
  notify:
    - docker_restart


- name: Add users into docker group
  user:
    append: yes
    name: "{{ item }}"
    groups: "{{ docker_group }}"
  with_items: "{{ docker_users }}"
  become: yes

